//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bililive_dm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bililive_dm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 非B站出品 ©2014-2020 CopyLiu 放棄所有權利 房間編號5051 問題反饋 copyliu@gmail.com 的本地化字符串。
        /// </summary>
        public static string ABout_Text {
            get {
                return ResourceManager.GetString("ABout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動重連 的本地化字符串。
        /// </summary>
        public static string AutoReconnect_Content {
            get {
                return ResourceManager.GetString("AutoReconnect.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開外掛程式資料夾 的本地化字符串。
        /// </summary>
        public static string Btn_Text_OpenPluginDir {
            get {
                return ResourceManager.GetString("Btn_Text_OpenPluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 還原默認 的本地化字符串。
        /// </summary>
        public static string Button_Content_Default {
            get {
                return ResourceManager.GetString("Button.Content.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測試效果 的本地化字符串。
        /// </summary>
        public static string Button_Content_Text {
            get {
                return ResourceManager.GetString("Button.Content.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更換主題 的本地化字符串。
        /// </summary>
        public static string ChangeSkin {
            get {
                return ResourceManager.GetString("ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空投喂統計 的本地化字符串。
        /// </summary>
        public static string ClearMe_Content {
            get {
                return ResourceManager.GetString("ClearMe.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空彈幕統計 的本地化字符串。
        /// </summary>
        public static string ClearMe2_Content {
            get {
                return ResourceManager.GetString("ClearMe2.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空用戶統計 的本地化字符串。
        /// </summary>
        public static string ClearMe3_Content {
            get {
                return ResourceManager.GetString("ClearMe3.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空彈幕統計(總) 的本地化字符串。
        /// </summary>
        public static string ClearMe4_Content {
            get {
                return ResourceManager.GetString("ClearMe4.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線 的本地化字符串。
        /// </summary>
        public static string ConnBtn_Content {
            get {
                return ResourceManager.GetString("ConnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式名稱 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式名稱 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式描述 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式作者 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式狀態 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin4 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式版本 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin5 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶名 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式描述 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        public static string DataGridTextColumn_Header3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斷開 的本地化字符串。
        /// </summary>
        public static string DisconnBtn_Content {
            get {
                return ResourceManager.GetString("DisconnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕姬視窗資料保護 的本地化字符串。
        /// </summary>
        public static string DisplayAffinity_Content {
            get {
                return ResourceManager.GetString("DisplayAffinity.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 規則運算式過濾 符合規則運算式的彈幕將不會出現在任何地方直接丟棄 的本地化字符串。
        /// </summary>
        public static string EnableRegex_Content {
            get {
                return ResourceManager.GetString("EnableRegex.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可為空 的本地化字符串。
        /// </summary>
        public static string FontSizeValidationRule_Validate_不可为空 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是數字 的本地化字符串。
        /// </summary>
        public static string FontSizeValidationRule_Validate_不是数字 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不是数字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必須是正數 的本地化字符串。
        /// </summary>
        public static string FontSizeValidationRule_Validate_必须是正数 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_必须是正数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕 的本地化字符串。
        /// </summary>
        public static string Full_Content {
            get {
                return ResourceManager.GetString("Full.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遮蔽刷屏(α) 的本地化字符串。
        /// </summary>
        public static string IgnoreSpam_Content {
            get {
                return ResourceManager.GetString("IgnoreSpam.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 觀客互動 的本地化字符串。
        /// </summary>
        public static string Interact_Content {
            get {
                return ResourceManager.GetString("Interact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 進入了直播間 的本地化字符串。
        /// </summary>
        public static string InteractType_Text1 {
            get {
                return ResourceManager.GetString("InteractType_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關注了直播間 的本地化字符串。
        /// </summary>
        public static string InteractType_Text2 {
            get {
                return ResourceManager.GetString("InteractType_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分享了直播間 的本地化字符串。
        /// </summary>
        public static string InteractType_Text3 {
            get {
                return ResourceManager.GetString("InteractType_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特別關注 的本地化字符串。
        /// </summary>
        public static string InteractType_Text4 {
            get {
                return ResourceManager.GetString("InteractType_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相互關注 的本地化字符串。
        /// </summary>
        public static string InteractType_Text5 {
            get {
                return ResourceManager.GetString("InteractType_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 的本地化字符串。
        /// </summary>
        public static string InteractType_TextFormat {
            get {
                return ResourceManager.GetString("InteractType_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了未知的互动事件 的本地化字符串。
        /// </summary>
        public static string InteractType_Unknown {
            get {
                return ResourceManager.GetString("InteractType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直播間地址: https://live.bilibili.com/ 的本地化字符串。
        /// </summary>
        public static string LiveRoomAddr {
            get {
                return ResourceManager.GetString("LiveRoomAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在自動重連... 的本地化字符串。
        /// </summary>
        public static string MainWindow_b_Disconnected_正在自动重连___ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_正在自动重连___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線被斷開 的本地化字符串。
        /// </summary>
        public static string MainWindow_b_Disconnected_連接被斷開 {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_連接被斷開", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線被斷開: 開發者資訊{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_b_Disconnected_連接被斷開__开发者信息_0_ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_連接被斷開__开发者信息_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直播間人數：{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_b_ReceivedRoomCount_ {
            get {
                return ResourceManager.GetString("MainWindow_b_ReceivedRoomCount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前房間人數:{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_b_ReceivedRoomCount_当前房间人数__0_ {
            get {
                return ResourceManager.GetString("MainWindow_b_ReceivedRoomCount_当前房间人数__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接房間號：{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID不合法 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_ID非法 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_ID非法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出錯資訊：{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_出錯 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_出錯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕姬報告 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_彈幕姬本身 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_彈幕姬本身", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在連線 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_正在连接 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_正在连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請輸入房間編碼,房間編碼是!數!字! 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線失敗 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_連接失敗 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_連接失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線成功 的本地化字符串。
        /// </summary>
        public static string MainWindow_connbtn_Click_連接成功 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_連接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   *Debug模式* 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_____Debug模式_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____Debug模式_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   *弱智版本* 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_____傻逼版本_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____傻逼版本_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   *原始資料輸出* 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_____原始数据输出_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____原始数据输出_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   版本號: 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow____版本号__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____版本号__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   編譯時間: 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow____编译时间__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____编译时间__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請有空發給聯繫方式 {0} 謝謝 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_Closed_报错 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_报错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_Closed_插件錯誤 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_插件錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕姬決定下版本開始停止支持Windows XP, 最低要求更改至 Win7 和 .NET 4.6.1,為保證你能在今後使用彈幕姬, 請安裝最新的 .net framework . 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_NetError {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_NetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的打開方式不正確 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_你的打开方式不正确 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_你的打开方式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告1: 由於廉價的證書供應商被某虎公司搞死了於是沒錢買證書了, 所以使用本軟體時可能會跳安全提示請無需理會. 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_公告1 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告2: 最近出現了一些所謂彈幕姬後續版, 聲稱本軟體已經不再更新, 並自稱後續版是原作者開發是新版云云. 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_公告2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 對此進行澄清, 彈幕姬從來也不會有任何的所謂後續版, 原作者直播間ID是5051, 任何非本人所開發的軟體的一切問題均不能解答. 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_公告2_2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 也請用戶在諮詢時, 確認清楚你所使用的軟體類型, 向正確的關係者諮詢. 謝謝. 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_公告2_3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告3: 投喂記錄不會在彈幕模式上出現, 這不是bug 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_公告3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以點擊日誌複製到剪貼簿 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_可以点击日志复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_可以点击日志复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前為Debug模式 的本地化字符串。
        /// </summary>
        public static string MainWindow_MainWindow_当前为Debug模式 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_当前为Debug模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開外掛程式資料夾出錯
        ///信息 的本地化字符串。
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_ {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開外掛程式資料夾出錯 的本地化字符串。
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错 {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Disable_插件報錯2 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Disable_插件報錯2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Enable_插件報錯 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_插件報錯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請有空發給聯繫方式 {0} 謝謝 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Enable_請有空發給聯繫方式__0__謝謝 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_請有空發給聯繫方式__0__謝謝", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !!!SuperChat!!! 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku____SuperChat___ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku____SuperChat___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 購買了 {1} x {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 贈送的: {1} x {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [爺] 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku__VIP前綴 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__VIP前綴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [管] 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku__管理員前綴_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__管理員前綴_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 進入直播間 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku__进入直播间 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__进入直播间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上船 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_上船 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_上船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上船:{0} 購買了 {1} x {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和管理 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_和管理 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_和管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總督 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_总督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_总督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提督 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_提督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_提督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到彈幕:{0}{1}{2} 說: {3} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到彈幕__0__1__2__說___3_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到彈幕__0__1__2__說___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到道具 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到道具:{0} 贈送的: {1} x {2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歡迎{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎_0_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歡迎{0}: {1}{2} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎_0____1__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎_0____1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歡迎老爺{0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎老爷_0_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎老爷_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歡迎老爺{0}: {1} 進入直播間 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎老爷_0____1__进入直播间 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎老爷_0____1__进入直播间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦長 的本地化字符串。
        /// </summary>
        public static string MainWindow_ProcDanmaku_舰长 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_舰长", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕姬測試 的本地化字符串。
        /// </summary>
        public static string MainWindow_Test_OnClick_彈幕姬測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_彈幕姬測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式彈幕測試 的本地化字符串。
        /// </summary>
        public static string MainWindow_Test_OnClick_插件彈幕測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_插件彈幕測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這不是個測試 的本地化字符串。
        /// </summary>
        public static string MainWindow_Test_OnClick_這不是個測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_這不是個測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 這是一個測試 的本地化字符串。
        /// </summary>
        public static string MainWindow_Test_OnClick_這是一個測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_這是一個測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本行記錄已複製到剪貼簿 的本地化字符串。
        /// </summary>
        public static string MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_PluginAdmin {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟用外掛程式 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_PluginEnabvle {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginEnabvle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用外掛程式 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_PluginStop {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投喂榜 的本地化字符串。
        /// </summary>
        public static string RankTabItem_Header {
            get {
                return ResourceManager.GetString("RankTabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存日誌 的本地化字符串。
        /// </summary>
        public static string SaveLog_Content {
            get {
                return ResourceManager.GetString("SaveLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕模式使用熒幕 的本地化字符串。
        /// </summary>
        public static string ScreenSelecter {
            get {
                return ResourceManager.GetString("ScreenSelecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顯示出錯信息 的本地化字符串。
        /// </summary>
        public static string ShowError_Content {
            get {
                return ResourceManager.GetString("ShowError.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 道具老爺 的本地化字符串。
        /// </summary>
        public static string ShowItem_Content {
            get {
                return ResourceManager.GetString("ShowItem.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側邊欄 的本地化字符串。
        /// </summary>
        public static string SideBar_Content {
            get {
                return ResourceManager.GetString("SideBar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主題選擇器 的本地化字符串。
        /// </summary>
        public static string SkinSelector {
            get {
                return ResourceManager.GetString("SkinSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偽春菜聯動 的本地化字符串。
        /// </summary>
        public static string SSTP_Content {
            get {
                return ResourceManager.GetString("SSTP.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 醒目留言:{0}{1}{2} 說: {3} 的本地化字符串。
        /// </summary>
        public static string SuperChatLogName {
            get {
                return ResourceManager.GetString("SuperChatLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首頁 的本地化字符串。
        /// </summary>
        public static string TabItem_Header {
            get {
                return ResourceManager.GetString("TabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式 的本地化字符串。
        /// </summary>
        public static string TabItem_Header_Plugin {
            get {
                return ResourceManager.GetString("TabItem.Header.Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設置 的本地化字符串。
        /// </summary>
        public static string TabItem_Header_Setting {
            get {
                return ResourceManager.GetString("TabItem.Header.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 說明 的本地化字符串。
        /// </summary>
        public static string TabItem_Header_Web {
            get {
                return ResourceManager.GetString("TabItem.Header.Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測試效果 的本地化字符串。
        /// </summary>
        public static string Test_Content {
            get {
                return ResourceManager.GetString("Test.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前人氣值: 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text {
            get {
                return ResourceManager.GetString("TextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意: 新彈幕引擎下文字速度選項無效 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_EnableNewEngineWarn {
            get {
                return ResourceManager.GetString("TextBlock.Text.EnableNewEngineWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕模式文字速度 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_FSpeed {
            get {
                return ResourceManager.GetString("TextBlock.Text.FSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕模式文字大小 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_FTextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.FTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外掛程式目錄: 我的文件\彈幕姬\Plugins 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_PluginDir {
            get {
                return ResourceManager.GetString("TextBlock.Text.PluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總共收到彈幕(原始資料) 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_R1 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總共收到彈幕(已顯示) 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_R2 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 參與評論的用戶 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_R3 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示文字出現時長 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SEff2Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff2Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示文字消失時長 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SEff3Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff3Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示出現時拉伸時長 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SEffTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示文字停留時長 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SKeepTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SKeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示出現時拉伸時長 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SShowTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側提示文字字體大小 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_STextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.STextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側窗口寬度 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SWidth {
            get {
                return ResourceManager.GetString("TextBlock.Text.SWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側窗口X偏移 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SXOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SXOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 側窗口Y偏移 的本地化字符串。
        /// </summary>
        public static string TextBlock_Text_SYOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SYOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口置頂 的本地化字符串。
        /// </summary>
        public static string WindowTop_Content {
            get {
                return ResourceManager.GetString("WindowTop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彈幕模式使用新彈幕引擎(Windows 8 以上) 的本地化字符串。
        /// </summary>
        public static string WTFEngineEnable_Content {
            get {
                return ResourceManager.GetString("WTFEngineEnable.Content", resourceCulture);
            }
        }
    }
}
