//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bililive_dm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bililive_dm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非B站出品 ©2014-2024 CopyLiu 放棄所有權利 房間編號5051 問題反饋 copyliu@gmail.com.
        /// </summary>
        public static string ABout_Text {
            get {
                return ResourceManager.GetString("ABout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動重連.
        /// </summary>
        public static string AutoReconnect_Content {
            get {
                return ResourceManager.GetString("AutoReconnect.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站直播中心返回了無效的房間號.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_B站直播中心返回了無效的房間號 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_B站直播中心返回了無效的房間號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站直播中心返回錯誤.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_B站直播中心返回錯誤 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_B站直播中心返回錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站直播中心離線.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_B站直播中心離線 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_B站直播中心離線", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未輸入身份碼.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_未輸入身份碼 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_未輸入身份碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獲取身份碼信息出錯.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_獲取身份碼信息出錯 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_獲取身份碼信息出錯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簽名伺服器離線.
        /// </summary>
        public static string BOpen_GetRoomIdByCode_簽名伺服器離線 {
            get {
                return ResourceManager.GetString("BOpen_GetRoomIdByCode_簽名伺服器離線", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打開外掛程式資料夾.
        /// </summary>
        public static string Btn_Text_OpenPluginDir {
            get {
                return ResourceManager.GetString("Btn_Text_OpenPluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 還原默認.
        /// </summary>
        public static string Button_Content_Default {
            get {
                return ResourceManager.GetString("Button.Content.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測試效果.
        /// </summary>
        public static string Button_Content_Text {
            get {
                return ResourceManager.GetString("Button.Content.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更換主題.
        /// </summary>
        public static string ChangeSkin {
            get {
                return ResourceManager.GetString("ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空投喂統計.
        /// </summary>
        public static string ClearMe_Content {
            get {
                return ResourceManager.GetString("ClearMe.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空彈幕統計.
        /// </summary>
        public static string ClearMe2_Content {
            get {
                return ResourceManager.GetString("ClearMe2.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空用戶統計.
        /// </summary>
        public static string ClearMe3_Content {
            get {
                return ResourceManager.GetString("ClearMe3.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空彈幕統計(總).
        /// </summary>
        public static string ClearMe4_Content {
            get {
                return ResourceManager.GetString("ClearMe4.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連線.
        /// </summary>
        public static string ConnBtn_Content {
            get {
                return ResourceManager.GetString("ConnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式名稱.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式描述.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式作者.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式狀態.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin4 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式版本.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin5 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用戶名.
        /// </summary>
        public static string DataGridTextColumn_Header1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數量.
        /// </summary>
        public static string DataGridTextColumn_Header2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物品.
        /// </summary>
        public static string DataGridTextColumn_Header3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斷開.
        /// </summary>
        public static string DisconnBtn_Content {
            get {
                return ResourceManager.GetString("DisconnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕姬視窗資料保護.
        /// </summary>
        public static string DisplayAffinity_Content {
            get {
                return ResourceManager.GetString("DisplayAffinity.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 規則運算式過濾 符合規則運算式的彈幕將不會出現在任何地方直接丟棄.
        /// </summary>
        public static string EnableRegex_Content {
            get {
                return ResourceManager.GetString("EnableRegex.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示字型.
        /// </summary>
        public static string FontFamilySelecter {
            get {
                return ResourceManager.GetString("FontFamilySelecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可為空.
        /// </summary>
        public static string FontSizeValidationRule_Validate_不可为空 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是數字.
        /// </summary>
        public static string FontSizeValidationRule_Validate_不是数字 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不是数字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必須是正數.
        /// </summary>
        public static string FontSizeValidationRule_Validate_必须是正数 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_必须是正数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕.
        /// </summary>
        public static string Full_Content {
            get {
                return ResourceManager.GetString("Full.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遮蔽表情.
        /// </summary>
        public static string IgnoreEmoji_Content {
            get {
                return ResourceManager.GetString("IgnoreEmoji.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遮蔽刷屏(α).
        /// </summary>
        public static string IgnoreSpam_Content {
            get {
                return ResourceManager.GetString("IgnoreSpam.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 觀客互動.
        /// </summary>
        public static string Interact_Content {
            get {
                return ResourceManager.GetString("Interact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 進入了直播間.
        /// </summary>
        public static string InteractType_Text1 {
            get {
                return ResourceManager.GetString("InteractType_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 關注了直播間.
        /// </summary>
        public static string InteractType_Text2 {
            get {
                return ResourceManager.GetString("InteractType_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 分享了直播間.
        /// </summary>
        public static string InteractType_Text3 {
            get {
                return ResourceManager.GetString("InteractType_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 將直播間加入到了特別關注.
        /// </summary>
        public static string InteractType_Text4 {
            get {
                return ResourceManager.GetString("InteractType_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 現在是相互關注.
        /// </summary>
        public static string InteractType_Text5 {
            get {
                return ResourceManager.GetString("InteractType_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 點了讚.
        /// </summary>
        public static string InteractType_Text6 {
            get {
                return ResourceManager.GetString("InteractType_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 发生了未知的互动事件.
        /// </summary>
        public static string InteractType_Unknown {
            get {
                return ResourceManager.GetString("InteractType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播間地址: https://live.bilibili.com/.
        /// </summary>
        public static string LiveRoomAddr {
            get {
                return ResourceManager.GetString("LiveRoomAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主播身份碼(在開播頁面獲取).
        /// </summary>
        public static string LiveRoomCode {
            get {
                return ResourceManager.GetString("LiveRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在自動重連....
        /// </summary>
        public static string MainWindow_b_Disconnected_正在自动重连___ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_正在自动重连___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連線被斷開.
        /// </summary>
        public static string MainWindow_b_Disconnected_連接被斷開 {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_連接被斷開", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連線被斷開: 開發者資訊{0}.
        /// </summary>
        public static string MainWindow_b_Disconnected_連接被斷開__开发者信息_0_ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_連接被斷開__开发者信息_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前人氣值：{0}.
        /// </summary>
        public static string MainWindow_b_ReceivedRoomCount_ {
            get {
                return ResourceManager.GetString("MainWindow_b_ReceivedRoomCount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連接房間號：{0}.
        /// </summary>
        public static string MainWindow_connbtn_Click_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID不合法.
        /// </summary>
        public static string MainWindow_connbtn_Click_ID非法 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_ID非法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出錯資訊：{0}.
        /// </summary>
        public static string MainWindow_connbtn_Click_出錯 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_出錯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕姬報告.
        /// </summary>
        public static string MainWindow_connbtn_Click_彈幕姬本身 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_彈幕姬本身", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在連線.
        /// </summary>
        public static string MainWindow_connbtn_Click_正在连接 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_正在连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入房間編碼,房間編碼是!數!字!.
        /// </summary>
        public static string MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連線失敗.
        /// </summary>
        public static string MainWindow_connbtn_Click_連接失敗 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_連接失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連線成功.
        /// </summary>
        public static string MainWindow_connbtn_Click_連接成功 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_連接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *Debug模式*.
        /// </summary>
        public static string MainWindow_MainWindow_____Debug模式_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____Debug模式_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *弱智版本*.
        /// </summary>
        public static string MainWindow_MainWindow_____傻逼版本_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____傻逼版本_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *原始資料輸出*.
        /// </summary>
        public static string MainWindow_MainWindow_____原始数据输出_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____原始数据输出_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   版本號:.
        /// </summary>
        public static string MainWindow_MainWindow____版本号__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____版本号__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   編譯時間:.
        /// </summary>
        public static string MainWindow_MainWindow____编译时间__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____编译时间__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站開放平台通知: 本次使用已結束, 請重新連線..
        /// </summary>
        public static string MainWindow_MainWindow_B站開放平台通知__本次使用已結束__請重新連線_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_B站開放平台通知__本次使用已結束__請重新連線_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請有空發給聯繫方式 {0} 謝謝.
        /// </summary>
        public static string MainWindow_MainWindow_Closed_报错 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_报错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2}.
        /// </summary>
        public static string MainWindow_MainWindow_Closed_插件錯誤 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_插件錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕姬決定下版本開始停止支持Windows XP, 最低要求更改至 Win7 和 .NET 4.6.1,為保證你能在今後使用彈幕姬, 請安裝最新的 .net framework ..
        /// </summary>
        public static string MainWindow_MainWindow_NetError {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_NetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的打開方式不正確.
        /// </summary>
        public static string MainWindow_MainWindow_你的打开方式不正确 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_你的打开方式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告1: 由於廉價的證書供應商被某虎公司搞死了於是沒錢買證書了, 所以使用本軟體時可能會跳安全提示請無需理會..
        /// </summary>
        public static string MainWindow_MainWindow_公告1 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告2: 最近出現了一些所謂彈幕姬後續版, 聲稱本軟體已經不再更新, 並自稱後續版是原作者開發是新版云云..
        /// </summary>
        public static string MainWindow_MainWindow_公告2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對此進行澄清, 彈幕姬從來也不會有任何的所謂後續版, 原作者直播間ID是5051, 任何非本人所開發的軟體的一切問題均不能解答..
        /// </summary>
        public static string MainWindow_MainWindow_公告2_2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 也請用戶在諮詢時, 確認清楚你所使用的軟體類型, 向正確的關係者諮詢. 謝謝..
        /// </summary>
        public static string MainWindow_MainWindow_公告2_3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告3: 投喂記錄不會在彈幕模式上出現, 這不是bug.
        /// </summary>
        public static string MainWindow_MainWindow_公告3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以點擊日誌複製到剪貼簿.
        /// </summary>
        public static string MainWindow_MainWindow_可以点击日志复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_可以点击日志复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前為Debug模式.
        /// </summary>
        public static string MainWindow_MainWindow_当前为Debug模式 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_当前为Debug模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打開外掛程式資料夾出錯
        ///信息.
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_ {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打開外掛程式資料夾出錯.
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错 {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2}.
        /// </summary>
        public static string MainWindow_Plugin_Disable_插件報錯2 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Disable_插件報錯2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式{0}遇到了不明錯誤: 日誌已經保存在桌面, 請有空發給該外掛程式作者 {1}, 聯繫方式 {2}.
        /// </summary>
        public static string MainWindow_Plugin_Enable_插件報錯 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_插件報錯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請有空發給聯繫方式 {0} 謝謝.
        /// </summary>
        public static string MainWindow_Plugin_Enable_請有空發給聯繫方式__0__謝謝 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_請有空發給聯繫方式__0__謝謝", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!SuperChat!!!.
        /// </summary>
        public static string MainWindow_ProcDanmaku____SuperChat___ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku____SuperChat___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \_q{0}\n\_q\f[height,20]{1}.
        /// </summary>
        public static string MainWindow_ProcDanmaku___SSPCommentFormat {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku___SSPCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 購買了 {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 贈送的: {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [爺].
        /// </summary>
        public static string MainWindow_ProcDanmaku__VIP前綴 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__VIP前綴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [管].
        /// </summary>
        public static string MainWindow_ProcDanmaku__管理員前綴_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__管理員前綴_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上船:{0} 購買了 {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總督.
        /// </summary>
        public static string MainWindow_ProcDanmaku_总督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_总督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督.
        /// </summary>
        public static string MainWindow_ProcDanmaku_提督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_提督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到彈幕:{0}{1}{2} 說: {3}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到彈幕__0__1__2__說___3_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到彈幕__0__1__2__說___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到道具.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到道具:{0} 贈送的: {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎{0}: {1} 進入直播間.
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎_0____1__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎_0____1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎老爺 {0} 進入直播間.
        /// </summary>
        public static string MainWindow_ProcDanmaku_歡迎老爺__0__進入直播間 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_歡迎老爺__0__進入直播間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎老爺和管理員 {0} 進入直播間.
        /// </summary>
        public static string MainWindow_ProcDanmaku_歡迎老爺和管理員__0__進入直播間 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_歡迎老爺和管理員__0__進入直播間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦長.
        /// </summary>
        public static string MainWindow_ProcDanmaku_舰长 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_舰长", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超管警告.
        /// </summary>
        public static string MainWindow_ProcDanmaku_超管警告 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_超管警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕姬測試.
        /// </summary>
        public static string MainWindow_Test_OnClick_彈幕姬測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_彈幕姬測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式彈幕測試.
        /// </summary>
        public static string MainWindow_Test_OnClick_插件彈幕測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_插件彈幕測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這不是個測試.
        /// </summary>
        public static string MainWindow_Test_OnClick_這不是個測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_這不是個測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這是一個測試.
        /// </summary>
        public static string MainWindow_Test_OnClick_這是一個測試 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_這是一個測試", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本行記錄已複製到剪貼簿.
        /// </summary>
        public static string MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        public static string MenuItem_Header_PluginAdmin {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啟用外掛程式.
        /// </summary>
        public static string MenuItem_Header_PluginEnabvle {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginEnabvle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停用外掛程式.
        /// </summary>
        public static string MenuItem_Header_PluginStop {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未啟用.
        /// </summary>
        public static string Plugin_DataGrid_Status_Off {
            get {
                return ResourceManager.GetString("Plugin_DataGrid_Status_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已啟用.
        /// </summary>
        public static string Plugin_DataGrid_Status_On {
            get {
                return ResourceManager.GetString("Plugin_DataGrid_Status_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投喂榜.
        /// </summary>
        public static string RankTabItem_Header {
            get {
                return ResourceManager.GetString("RankTabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存日誌.
        /// </summary>
        public static string SaveLog_Content {
            get {
                return ResourceManager.GetString("SaveLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕模式使用熒幕.
        /// </summary>
        public static string ScreenSelecter {
            get {
                return ResourceManager.GetString("ScreenSelecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示出錯信息.
        /// </summary>
        public static string ShowError_Content {
            get {
                return ResourceManager.GetString("ShowError.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道具老爺.
        /// </summary>
        public static string ShowItem_Content {
            get {
                return ResourceManager.GetString("ShowItem.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側邊欄.
        /// </summary>
        public static string SideBar_Content {
            get {
                return ResourceManager.GetString("SideBar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主題選擇器.
        /// </summary>
        public static string SkinSelector {
            get {
                return ResourceManager.GetString("SkinSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偽春菜聯動.
        /// </summary>
        public static string SSTP_Content {
            get {
                return ResourceManager.GetString("SSTP.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 醒目留言:{0}{1}{2} 說: {3}.
        /// </summary>
        public static string SuperChatLogName {
            get {
                return ResourceManager.GetString("SuperChatLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        public static string TabItem_Header {
            get {
                return ResourceManager.GetString("TabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式.
        /// </summary>
        public static string TabItem_Header_Plugin {
            get {
                return ResourceManager.GetString("TabItem.Header.Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設置.
        /// </summary>
        public static string TabItem_Header_Setting {
            get {
                return ResourceManager.GetString("TabItem.Header.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 說明.
        /// </summary>
        public static string TabItem_Header_Web {
            get {
                return ResourceManager.GetString("TabItem.Header.Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測試效果.
        /// </summary>
        public static string Test_Content {
            get {
                return ResourceManager.GetString("Test.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人氣值:.
        /// </summary>
        public static string TextBlock_Text {
            get {
                return ResourceManager.GetString("TextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意: 新彈幕引擎下文字速度選項無效.
        /// </summary>
        public static string TextBlock_Text_EnableNewEngineWarn {
            get {
                return ResourceManager.GetString("TextBlock.Text.EnableNewEngineWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕模式文字速度.
        /// </summary>
        public static string TextBlock_Text_FSpeed {
            get {
                return ResourceManager.GetString("TextBlock.Text.FSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕模式文字大小.
        /// </summary>
        public static string TextBlock_Text_FTextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.FTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外掛程式目錄: 我的文件\弹幕姬\Plugins.
        /// </summary>
        public static string TextBlock_Text_PluginDir {
            get {
                return ResourceManager.GetString("TextBlock.Text.PluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總共收到彈幕(原始資料).
        /// </summary>
        public static string TextBlock_Text_R1 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總共收到彈幕(已顯示).
        /// </summary>
        public static string TextBlock_Text_R2 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 參與評論的用戶.
        /// </summary>
        public static string TextBlock_Text_R3 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示文字出現時長.
        /// </summary>
        public static string TextBlock_Text_SEff2Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff2Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示文字消失時長.
        /// </summary>
        public static string TextBlock_Text_SEff3Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff3Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示出現時拉伸時長.
        /// </summary>
        public static string TextBlock_Text_SEffTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示文字停留時長.
        /// </summary>
        public static string TextBlock_Text_SKeepTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SKeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示出現時拉伸時長.
        /// </summary>
        public static string TextBlock_Text_SShowTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側提示文字字型大小.
        /// </summary>
        public static string TextBlock_Text_STextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.STextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側窗口寬度.
        /// </summary>
        public static string TextBlock_Text_SWidth {
            get {
                return ResourceManager.GetString("TextBlock.Text.SWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側窗口X偏移.
        /// </summary>
        public static string TextBlock_Text_SXOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SXOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 側窗口Y偏移.
        /// </summary>
        public static string TextBlock_Text_SYOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SYOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 觀看人次:.
        /// </summary>
        public static string WatchedCount {
            get {
                return ResourceManager.GetString("WatchedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口置頂.
        /// </summary>
        public static string WindowTop_Content {
            get {
                return ResourceManager.GetString("WindowTop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彈幕模式使用新彈幕引擎(Windows 8 以上).
        /// </summary>
        public static string WTFEngineEnable_Content {
            get {
                return ResourceManager.GetString("WTFEngineEnable.Content", resourceCulture);
            }
        }
    }
}
